# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copies_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='readerslistrecord',
            name='date_returned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
