# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
