# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20170524_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='hidden',
        ),
        migrations.AddField(
            model_name='book',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
