# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='read_books',
            field=models.ManyToManyField(to='books.Book'),
        ),
    ]
