# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_read_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='read_books',
            field=models.ManyToManyField(blank=True, to='books.Book'),
        ),
    ]
